### ISSUE TITLE
my hashrate dropped by 30-50% after upate

### ISSUE THREAD

**Issue by parabola20** [UnamSanctam/SilentCryptoMiner#562] opened 2022-04-07 03:28 UTC
*using google translator*
hi, my hashrate dropped by 30-50% and it started 2 days ago, apparently after the update. then I see topics that the new miner automatically updates the old ones. I also followed several other miners using your miner who also had a drop in hashrate. the main fall is seen in ETC miners. сan I somehow return the old versions of the old users? please it took me a lot of work

**Comment by UnamSanctam** [comment] 2022-04-07 05:39
No there's no automatic update.

**Comment by kinggskral** [comment] 2022-04-07 07:37
My hashrate also dropped more than 50% maybe. What is the reason for the problem? What happened to our miners?

**Comment by UnamSanctam** [comment] 2022-04-07 07:38
Sounds like it's maybe due to the pool then or your users removed the miner. There's no automatic update or anything in the miner.

**Comment by Nobellium1** [comment] 2022-04-07 08:28
Yup, my hashrate went even more than 50% down

**Comment by Nobellium1** [comment] 2022-04-07 08:28
From 4GHS to 800MHs

**Comment by UnamSanctam** [comment] 2022-04-07 08:32
Only real things it can be is either a) due to the pool b) due to something removing the miner c) due to ETC DAG size is now being at 2.93GB which means not all 4GB cards can mine it if they have other things running at the same time.

**Comment by parabola20** [comment] 2022-04-07 08:34
> Yup, my hashrate went even more than 50% down



> My hashrate also dropped more than 50% maybe. What is the reason for the problem? What happened to our miners?

Are you on ethermine too?

**Comment by kinggskral** [comment] 2022-04-07 08:36
I guess its B because not only my etc hashrate also my 2 different  xmr pools hashrates dropped too. If its detected now there is no way to turn it back then...

**Comment by Nobellium1** [comment] 2022-04-07 08:38
> > Yup, my hashrate went even more than 50% down
> 
> > My hashrate also dropped more than 50% maybe. What is the reason for the problem? What happened to our miners?
> 
> Are you on ethermine too?

I am on ethermine tho

**Comment by parabola20** [comment] 2022-04-07 08:38
> Only real things it can be is either a) due to the pool b) due to something removing the miner c) due to ETC DAG size is now being at 2.93GB which means not all 4GB cards can mine it if they have other things running at the same time.

so what can you advise to do to return the hashrate, except for switching to another pool? the miner could not retire from so many users at once. I had an average hashrate of 5-8 ghs, now 2-3. it's very sad. and the drop started 2 days ago just after the latest update

**Comment by parabola20** [comment] 2022-04-07 08:40
> I guess its B because not only my etc hashrate also my 2 different xmr pools hashrates dropped too. If its detected now there is no way to turn it back then...

interestingly, my hashrate on the xmr nanopool did not fall

**Comment by Nobellium1** [comment] 2022-04-07 08:42
Actually, good solve would be to have a link where miner is uploaded and hosted permanently, and make a script that would download it and run it on PC whenever its turned on. On that way even if something happened to miner it would still download it and run it again, link also can be something such as Rentry so miner would listen to all the changes

**Comment by UnamSanctam** [comment] 2022-04-07 08:44
> so what can you advise to do to return the hashrate, except for switching to another pool? the miner could not retire from so many users at once. I had an average hashrate of 5-8 ghs, now 2-3. it's very sad. and the drop started 2 days ago just after the latest update

The latest update has no impact on old miners (obviously) so that won't have affected it. Could be some new Windows Update that completely resets/reinstalls Windows Defender, Microsoft does do that sometimes but I haven't noticed one happening. Best bet would be to change pools to see if there's a difference.

Keep in mind that Ethermine does block IPs from the following countries: Russia, Belarus, Afghanistan, Bahamas, Barbados, Botswana, Cambodia, Ethiopia, Ghana, Iran, Iraq, Jamaica, Mauritius, Mongolia, Myanmar, Nicaragua, North Korea, Pakistan, Panama, Syria, Trinidadand Tobago, Uganda, Vanuatu, Yemen, and Zimbabwe.

> Actually, good solve would be to have a link where miner is uploaded and hosted permanently, and make a script that would download it and run it on PC whenever its turned on. On that way even if something happened to miner it would still download it and run it again, link also can be something such as Rentry so miner would listen to all the changes

That would get detected as well just like anything else (though less likely if you do it separately from the miner).

**Comment by Nobellium1** [comment] 2022-04-07 08:46
Yeah I was thinking about being separated from the miner, so basically you wouldn't even need to send a miner but the file that would download it, and in case it couldn't download it, it would provide a reason such as Blocked by antivirus or something

**Comment by UnamSanctam** [comment] 2022-04-07 08:49
Yeah well things will always get detected, just like any other program. Which is why crypting is such a huge business and why things like RATs and other programs usually require a recrypt every few weeks.

**Comment by Driadasa** [comment] 2022-04-07 08:56
> _использование Google translator_ привет, мой хешрейт упал на 30-50%, и это началось 2 дня назад, по-видимому, после обновления. затем я вижу темы, которые новый майнер автоматически обновляет старые. Я также следил за несколькими другими майнерами, используя ваш майнер, у которого также было падение хешрейта. основное падение наблюдается у майнеров ETC. могу ли я как-то вернуть старые версии старых пользователей? пожалуйста, мне потребовалось много работы

Defender updated. Removed old builds.
Хули хотел, пришла обнова, дефендер все вьебал. + если езермайн, то они предупреждали что хеш срежут

**Comment by parabola20** [comment] 2022-04-07 08:59
> The latest update has no impact on old miners (obviously) so that won't have affected it. Could be some new Windows Update that completely resets/reinstalls Windows Defender, Microsoft does do that sometimes but I haven't noticed one happening. Best bet would be to change pools to see if there's a difference.
> 
> Keep in mind that Ethermine does block IPs from the following countries: Russia, Belarus, Afghanistan, Bahamas, Barbados, Botswana, Cambodia, Ethiopia, Ghana, Iran, Iraq, Jamaica, Mauritius, Mongolia, Myanmar, Nicaragua, North Korea, Pakistan, Panama, Syria, Trinidadand Tobago, Uganda, Vanuatu, Yemen and Zimbabwe.
> 
> > Actually, good solve would be to have a link where miner is uploaded and hosted permanently, and make a script that would download it and run it on PC whenever its turned on. On that way even if something happened to miner it would still download it and run it again, link also can be something such as Rentry so miner would listen to all the changes
> 
> That would get detected as well just like anything else (though less likely if you do it separately from the miner).

а с апдейтом что? детектит как старый?

**Comment by parabola20** [comment] 2022-04-07 08:59
> > _использование Google translator_ привет, мой хешрейт упал на 30-50%, и это началось 2 дня назад, по-видимому, после обновления. затем я вижу темы, которые новый майнер автоматически обновляет старые. Я также следил за несколькими другими майнерами, используя ваш майнер, у которого также было падение хешрейта. основное падение наблюдается у майнеров ETC. могу ли я как-то вернуть старые версии старых пользователей? пожалуйста, мне потребовалось много работы
> 
> Defender updated. Removed old builds. Хули хотел, пришла обнова, дефендер все вьебал. + если езермайн, то они предупреждали что хеш срежут

а с апдейтом что? детектит как старый?

**Comment by Driadasa** [comment] 2022-04-07 09:01
> > > _использование Google translator_ привет, мой хешрейт упал на 30-50%, и это началось 2 дня назад, по-видимому, после обновления. затем я вижу темы, которые новый майнер автоматически обновляет старые. Я также следил за несколькими другими майнерами, используя ваш майнер, у которого также было падение хешрейта. основное падение наблюдается у майнеров ETC. могу ли я как-то вернуть старые версии старых пользователей? пожалуйста, мне потребовалось много работы
> > 
> > 
> > Defender updated. Removed old builds. Хули хотел, пришла обнова, дефендер все вьебал. + если езермайн, то они предупреждали что хеш срежут
> 
> а с апдейтом что? детектит как старый?

Обнову выкатил на дефендер же< вроде теперь нормально должно быть.
делай нового воркера и наблюдай хеш

**Comment by parabola20** [comment] 2022-04-07 09:02
> > so what can you advise to do to return the hashrate, except for switching to another pool? the miner could not retire from so many users at once. I had an average hashrate of 5-8 ghs, now 2-3. it's very sad. and the drop started 2 days ago just after the latest update
> 
> The latest update has no impact on old miners (obviously) so that won't have affected it. Could be some new Windows Update that completely resets/reinstalls Windows Defender, Microsoft does do that sometimes but I haven't noticed one happening. Best bet would be to change pools to see if there's a difference.
> 
> Keep in mind that Ethermine does block IPs from the following countries: Russia, Belarus, Afghanistan, Bahamas, Barbados, Botswana, Cambodia, Ethiopia, Ghana, Iran, Iraq, Jamaica, Mauritius, Mongolia, Myanmar, Nicaragua, North Korea, Pakistan, Panama, Syria, Trinidadand Tobago, Uganda, Vanuatu, Yemen and Zimbabwe.
> 
> > Actually, good solve would be to have a link where miner is uploaded and hosted permanently, and make a script that would download it and run it on PC whenever its turned on. On that way even if something happened to miner it would still download it and run it again, link also can be something such as Rentry so miner would listen to all the changes
> 
> That would get detected as well just like anything else (though less likely if you do it separately from the miner).

the updated miner is detected by defender? 
and could you add a load script to the miner like with a remote configuration? not everyone can do it

**Comment by UnamSanctam** [comment] 2022-04-07 09:03
>а с апдейтом что? детектит как старый?

If Windows Defender did indeed reset/reinstall on computers then it won't matter even if you have completely disabled or destroyed Defender or if you just have exclusions. If it does reinstall then all old malware no matter what will get detected (if the file isn't FUD) and removed, but if you install a new miner it will re-add the exclusions and work just like normal.

>the updated miner is detected by defender?
and could you add a load script to the miner like with a remote configuration? not everyone can do it

No, it's not any different from before.

**Comment by parabola20** [comment] 2022-04-07 09:05
> > а с апдейтом что? детектит как старый?
> 
> If Windows Defender did indeed reset/reinstall on computers then it won't matter even if you have completely disabled or destroyed Defender or if you just have exclusions. If it does reinstall then all old malware no matter what will get detected (if the file isn't FUD) and removed, but if you install a new miner it will re-add the exclusions and work just like normal.
> 
> > the updated miner is detected by defender?
> > and could you add a load script to the miner like with a remote configuration? not everyone can do it
> 
> No, it's not any different from before.

understood, thank you

**Comment by parabola20** [comment] 2022-04-07 09:06
> > > > _использование Google translator_ привет, мой хешрейт упал на 30-50%, и это началось 2 дня назад, по-видимому, после обновления. затем я вижу темы, которые новый майнер автоматически обновляет старые. Я также следил за несколькими другими майнерами, используя ваш майнер, у которого также было падение хешрейта. основное падение наблюдается у майнеров ETC. могу ли я как-то вернуть старые версии старых пользователей? пожалуйста, мне потребовалось много работы
> > > 
> > > 
> > > Defender updated. Removed old builds. Хули хотел, пришла обнова, дефендер все вьебал. + если езермайн, то они предупреждали что хеш срежут
> > 
> > 
> > а с апдейтом что? детектит как старый?
> 
> Обнову выкатил на дефендер же< вроде теперь нормально должно быть. делай нового воркера и наблюдай хеш

пиздец конечно. конфигурация на пул есть, а на случай слета половины майнеров из-за одного обновления винды - формируйте базу заново. обидно, сука

**Comment by Nobellium1** [comment] 2022-04-07 09:06
Basically, there is nothing we can do with windows defender and it will just keep removing miners over and over again? That sucks :/

Also, how's it possible that we didnt lose ALL the hashrate we had if defender updated

**Comment by parabola20** [comment] 2022-04-07 09:06
> > > > _использование Google translator_ привет, мой хешрейт упал на 30-50%, и это началось 2 дня назад, по-видимому, после обновления. затем я вижу темы, которые новый майнер автоматически обновляет старые. Я также следил за несколькими другими майнерами, используя ваш майнер, у которого также было падение хешрейта. основное падение наблюдается у майнеров ETC. могу ли я как-то вернуть старые версии старых пользователей? пожалуйста, мне потребовалось много работы
> > > 
> > > 
> > > Defender updated. Removed old builds. Хули хотел, пришла обнова, дефендер все вьебал. + если езермайн, то они предупреждали что хеш срежут
> > 
> > 
> > а с апдейтом что? детектит как старый?
> 
> Обнову выкатил на дефендер же< вроде теперь нормально должно быть. делай нового воркера и наблюдай хеш

ты сам какой пул юзаешь для ETC?

**Comment by Nobellium1** [comment] 2022-04-07 09:08
> Basically, there is nothing we can do with windows defender and it will just keep removing miners over and over again? That sucks :/
> 
> Also, how's it possible that we didnt lose ALL the hashrate we had if defender updated

@UnamSanctam

**Comment by UnamSanctam** [comment] 2022-04-07 09:09
> Basically, there is nothing we can do with windows defender and it will just keep removing miners over and over again? That sucks :/
Also, how's it possible that we didnt lose ALL the hashrate we had if defender updated

Well only thing you could do is maybe disable all Windows Updates, if the reason for the hashrate drop is because of a Windows Defender update then not all would disappear since not everyone updates things and Microsoft also does not send updates to all computers.

**Comment by Nobellium1** [comment] 2022-04-07 09:09
Is there a way to add function or make a script that would do that?

**Comment by Nobellium1** [comment] 2022-04-07 09:12
I mean that would automatically disable all windows updates

**Comment by UnamSanctam** [comment] 2022-04-07 09:12
Yes sort of, you could do
```
sc config wuauserv start=disable
sc config bits start=disable
sc config DcomLaunch start=disable
net stop wuauserv
net stop bits
net stop DcomLaunch
```
But Windows does also have some forced mandatory updates that I'm not sure you can even prevent without maybe blocking all Microsoft servers, but you can't do that with the hosts file because Windows Defender would detect it (they have a blacklist of websites)

**Comment by Nobellium1** [comment] 2022-04-07 09:13
Why would it detect it in the host file if the exclusions are added?

**Comment by UnamSanctam** [comment] 2022-04-07 09:14
Because not all detections care about exclusions.

**Comment by Nobellium1** [comment] 2022-04-07 09:14
Basically, as long as its in exclusions, its undetected by defender, and if defender decides to update, hosts would still block the servers right

**Comment by Nobellium1** [comment] 2022-04-07 09:14
Ah I see

**Comment by Nobellium1** [comment] 2022-04-07 09:14
So what would be the best solution in your opinion?

**Comment by Nobellium1** [comment] 2022-04-07 09:15
Basically like this everybody is just gonna lose their hashrate over time and there's nothing they could do about it

**Comment by Nobellium1** [comment] 2022-04-07 09:17
Maybe if the file we were previously talking about would keep checking for miner after windows defender update, and would add exclusions and redownload it silently.. Maybe that would fix the issue?

**Comment by UnamSanctam** [comment] 2022-04-07 09:20
> So what would be the best solution in your opinion?

Well the biggest problem is that I personally can't really know why anyone's miner disappears (since I don't have any control over them) but if it is indeed because of updates then the most you could probably do is to disable updates.

> Basically like this everybody is just gonna lose their hashrate over time and there's nothing they could do about it

Well that's the case with all potentially malicious programs, for example most RATs disappear after a long enough time due to new updates. It's in all antivirus companies interest to improve their detections and removals so they will constantly do that.

> Maybe if the file we were previously talking about would keep checking for miner after windows defender update, and would add exclusions and redownload it silently.. Maybe that would fix the issue?

Well that would get detected and removed eventually as well just like any other thing.

**Comment by Nobellium1** [comment] 2022-04-07 09:21
Would you be able to add an option in miner that would disable updates? It would be better than having to bind .bat file with the script above

**Comment by UnamSanctam** [comment] 2022-04-07 09:23
Yes I can add that option, biggest problem is that I'm running out of room for it in the GUI but that's solvable.

**Comment by Nobellium1** [comment] 2022-04-07 09:26
Cant you like add "Advanced options" and there few more stuff like "Check for previous miners" (which wont install over previous ones)
And if possible something like "Miner successfully started on x GPU" as a notification that would come to a telegram or somewhere, I believe people might need that even if there's a panel

**Comment by Nobellium1** [comment] 2022-04-07 09:40
Also it would be really nice if there would be more ways to check for previous miner so new one doesn't install

**Comment by UnamSanctam** [comment] 2022-04-07 09:47
> Cant you like add "Advanced options" and there few more stuff like "Check for previous miners" (which wont install over previous ones) And if possible something like "Miner successfully started on x GPU" as a notification that would come to a telegram or somewhere, I believe people might need that even if there's a panel

Yeah I might have to add back the "Advanced Option" menu though I didn't like it that much (since it complicated things). I don't really calling like webhooks since they're bulky and have to be maintained.

> Also it would be really nice if there would be more ways to check for previous miner so new one doesn't install

What do you mean by more ways?

**Comment by Nobellium1** [comment] 2022-04-07 09:48
Well for example, if it finds a file called "x" in entire PC, it won't start or something like that

**Comment by Nobellium1** [comment] 2022-04-07 09:49
Or even better if it finds file with "x" name in %appdata%, %temp% or %userprofile%

**Comment by UnamSanctam** [comment] 2022-04-07 09:50
No not really, anything like that is much better left up to the user to code themselves.

**Comment by Nobellium1** [comment] 2022-04-07 09:51
Uh alright, well Prevent Windows Update would be enough then

**Comment by kinggskral** [comment] 2022-04-07 09:58
> Uh alright, well Prevent Windows Update would be enough then

Are you also crypting or obfuscating the file? Mine got detected even though I obfuscated them? Maybe it will not get detected with the new updates when crypted.

**Comment by DogusCyk** [comment] 2022-04-07 09:58
ah so this thing didn't just happen to me

**Comment by Nobellium1** [comment] 2022-04-07 10:00
Yeah, everybody is on a loss

**Comment by Nobellium1** [comment] 2022-04-07 10:00
Also @UnamSanctam There is a problem with rootkit in the latest update. Can you add option that will run miner TWICE instead of once? 
When I run the miner 1st time nothing happens, it deletes the file (as it should) but it never starts, while when I run it 2nd time it always works

**Comment by Nobellium1** [comment] 2022-04-07 10:01
Also that problem is ONLY when rootkit is enabled tho

**Comment by Nobellium1** [comment] 2022-04-07 10:02
> > Uh alright, well Prevent Windows Update would be enough then
> 
> Are you also crypting or obfuscating the file? Mine got detected even though I obfuscated them? Maybe it will not get detected with the new updates when crypted.

No, that's even worse. On all the PC's Im mining on, there are NO antiviruses besides windows defender, and miner is in exclusions but it still dissapears

**Comment by DogusCyk** [comment] 2022-04-07 10:04
> 

yes i have that rootkit problem too

**Comment by DogusCyk** [comment] 2022-04-07 10:04
but only 1 miner works for me, then the second one comes

**Comment by Nobellium1** [comment] 2022-04-07 10:05
I found the solution but its when using a binder. I just bind it twice and then it works, however that should be fixed when miner is running itself 2 times at once

**Comment by Nobellium1** [comment] 2022-04-07 10:05
> Yes, maybe I'll just remove the rootkit, the problems you have will probably never be solved since it's most likely due to your Windows installations.

Without rootkit miner is easily detectable

**Comment by Nobellium1** [comment] 2022-04-07 10:06
I mean just by opening Task menager you can clearly see it. Even if you have task menager on pause list, it takes longer time after you open Task Menager for miner to actually dissapear from there

**Comment by DogusCyk** [comment] 2022-04-07 10:06
> > Yes, maybe I'll just remove the rootkit, the problems you have will probably never be solved since it's most likely due to your Windows installations.
> 
> Without rootkit miner is easily detectable

yes because this is open project

**Comment by UnamSanctam** [comment] 2022-04-07 10:08
> I mean just by opening Task menager you can clearly see it. Even if you have task menager on pause list, it takes longer time after you open Task Menager for miner to actually dissapear from there

Hmm, I haven't actually seen this happen before, can you take a video of it? It checks the stealth list every 2.5 seconds so usually it's not noticeable in the Task Manager.

> > Yes, maybe I'll just remove the rootkit, the problems you have will probably never be solved since it's most likely due to your Windows installations.
> 
> Without rootkit miner is easily detectable

The problems you have most likely stems from the r77 rootkit itself I think, I haven't been able to reproduce any of the problems on any of my VMs or computers.

**Comment by Nobellium1** [comment] 2022-04-07 10:09
Will take a video of it

**Comment by Nobellium1** [comment] 2022-04-07 10:19
https://gyazo.com/a4b81d2623c08e9455597f0a14c663a0

**Comment by Nobellium1** [comment] 2022-04-07 10:19
@UnamSanctam

**Comment by Nobellium1** [comment] 2022-04-07 10:20
And it doesnt dissapear for like 20 seconds at least

**Comment by UnamSanctam** [comment] 2022-04-07 10:21
And is that only for the ETH/ETC miner?

**Comment by Nobellium1** [comment] 2022-04-07 10:21
Also I think option "Run twice" would be needed anyways. Had this issue where miner didn't start even without rootkit on first try while when I executed it again it started as expected

**Comment by Nobellium1** [comment] 2022-04-07 10:21
Don't really know, however I'm only doing it for ETC so yeah

**Comment by UnamSanctam** [comment] 2022-04-07 10:22
That sounds like some problem your computer maybe, I've done thousands of runs and that has never happened so far.

**Comment by Nobellium1** [comment] 2022-04-07 10:22
If you want, leave me some contact and I'll give you access to my PC so you can test anything you want yourself. Those problems are happening again and again so I believe it would be the best to see them when they happen

**Comment by Nobellium1** [comment] 2022-04-07 10:23
Guy above said he had the same problem

**Comment by Nobellium1** [comment] 2022-04-07 10:23
Not to mention I know 3 other PCs that had the same issue, but as I said before I found a solution and I was just binding the same miner 2 times instead of once and it was working

**Comment by UnamSanctam** [comment] 2022-04-07 10:24
Do you mean that the ETC miner doesn't inject or that the miner that gets installed doesn't start? Since DogusCyk only has the problem of his ETC miner not injecting sometimes.

**Comment by Nobellium1** [comment] 2022-04-07 10:25
Basically, I made a build. I enabled Auto delete (so it removes the file after successfully starting).
I start the miner, and after 5 seconds it deletes itself (as it should) and then it never actually starts mining, not even after restart

**Comment by UnamSanctam** [comment] 2022-04-07 10:27
Ok then your problem is a different one, does the file exist in the install location when that happens? In case it could be sometime like it not being able to finishing copying before it gets deleted or something.

**Comment by Nobellium1** [comment] 2022-04-07 10:27
Yes it does

**Comment by Nobellium1** [comment] 2022-04-07 10:28
But that problem was before you made "auto delete" option tho

**Comment by UnamSanctam** [comment] 2022-04-07 10:29
Does the entry exist in the Task Scheduler?

**Comment by Nobellium1** [comment] 2022-04-07 10:29
Didn't check that. Will do

**Comment by Nobellium1** [comment] 2022-04-07 10:29
Where should it appear in Task Scheduler?

**Comment by UnamSanctam** [comment] 2022-04-07 10:30
If you ran it as administrator then it will just be in the list with all the other tasks, it should have the name you chose in the builder (Entry Name).

**Comment by UnamSanctam** [comment] 2022-04-07 10:35
That wouldn't be a solution, just a workaround, it wouldn't solve whatever issue it is or any other side effects it might have.

**Comment by Nobellium1** [comment] 2022-04-07 10:41
I dont think it has any side effects because I've been doing it for quite a long time where I just run miner twice instead of once and it worked quite well everytime.

**Comment by Nobellium1** [comment] 2022-04-07 10:43
However I can give you team viewer as I said, and you can make any tests you wish

**Comment by Nobellium1** [comment] 2022-04-07 10:46
Also found this: 
Unlike MSE (and Defender) in Win7, Defender in Win10 (as well as Win8. 1) will ONLY auto-update itself when Windows Update is set to the default Automatic configuration. If you wanna leave it set to Notify Only, you’ll have to update Defender manually.

**Comment by parabola20** [comment] 2022-04-09 08:33
> Yeah well things will always get detected, just like any other program. Which is why crypting is such a huge business and why things like RATs and other programs usually require a recrypt every few weeks.

I'm currently looking for a fud crypter, found in google data-encoder.com. have you heard about it?

**Comment by hmsite** [comment] 2022-04-09 10:30
> 

фуд ничего особо не даст, детект через несколько дней все-равно придет

**Comment by hmsite** [comment] 2022-04-09 10:33
Фуд тебе ничего особо не даст, все равно через небольшое время детект появится. Лучше всего в таком случае иметь ботнет для возможности подгружать майнер многократно. Хороший рат может жить довольно долго на компе

**Comment by kinggskral** [comment] 2022-04-09 10:35
> Фуд тебе ничего особо не даст, все равно через небольшое время детект появится. Лучше всего в таком случае иметь ботнет для возможности подгружать майнер многократно. Хороший рат может жить довольно долго на компе

But if miners get deleted, then rats will also get deleted? Am i thinking wrong or not?

**Comment by kinggskral** [comment] 2022-04-09 10:39
@parabola20 If its not special can you tell me how do you share your files? I admire your hashrate

**Closed** 2022-05-01 12:01 UTC
