### ISSUE TITLE
Unable to mine RVN using kawpow

### ISSUE THREAD

**Issue by explowz** [UnamSanctam/SilentCryptoMiner#508] opened 2022-03-28 18:18 UTC
When trying to create a kawpow miner, it uses the same settings as if I were to try and set up an XMR miner, even though RVN can only be mined using kawpow, which mines on the GPU, not on the CPU. As of right now, I cannot set any GPU percentage to mine using kawpow, since there is no such option. The options for setting up a kawpow miner should look the same as if I were to set up an ETH miner.

**Comment by UnamSanctam** [comment] 2022-03-28 22:03
KawPow is mined using xmrig so it should be the same as the XMR miner, there are some issues with xmrigs GPU libraries for Nvidia (as always) which will be fixed in the next version.

**Comment by explowz** [comment] 2022-03-29 17:16
KawPow is mined using GMiner, teamredminer or T-Rex, so GPU miners. From what I know, you cannot mine kawpow on the CPU. You can check articles on the Internet. A simple search «How to mine RVN?» will show you that it's mined using the GPU. It can be mined with xmrig, since xmrig can also mine using the GPU, but all sites recommend GMiner and other GPU-only miners, the same miners used for mining ETH.

**Comment by UnamSanctam** [comment] 2022-03-29 17:26
Yes but creating a new miner and all the features for it just for Ravencoin is not something I want to do, especially since KawPow isn't a very good algorithm to silent mine due to the intensity of it.

**Comment by explowz** [comment] 2022-03-29 17:50
Ok, so, as of right now, there's not really any way of silently mining RVN? Is it not possible to set xmrig to mine with the GPU only when the computer is idle? There's the Max CPU and Idle CPU option. Is there no way to just make it not mine on the GPU at all when the user is active?

**Comment by UnamSanctam** [comment] 2022-03-29 17:55
Not really right now, due to how XMRig has implemented CUDA and OpenCL it's quite difficult to limit the GPU in an efficient manner (from my tests of doing that so far). I can look into implementing it but right now ETH and ETC are more profitable and efficient to mine than RVN on most cards so I'm focusing on those.

**Comment by explowz** [comment] 2022-03-29 18:05
I understand. It's not that big of a deal if you don't want to implement RVN into a GPU only miner. I'm just asking if you could add (or if there's already a way) to make the xmrig miner only start when the user is idle and only mine using the GPU. As of right now this can be done with the CPU miner, but from what I've tried, not witht the xmrig GPU part of the miner.

**Comment by UnamSanctam** [comment] 2022-03-29 18:14
If you disable "CPU Mining" and enable "GPU Mining" it will only mine with the GPU, you can't mine KawPow with the CPU in XMRig anyways. But if you set "Max CPU" to 0% and "Idle CPU" to anything above 0% it technically should do what you want it to do since what it does then is pause the entire miner while the computer is being used and resume when it's idle. The problem right now is with the xmrig CUDA library which I'm "fixing" in the next version.

The reason I don't want to implement KawPow into ethminer (the GPU miner I use right now, and one of the few only open source ones) right now is that it would probably take around 50-100 hours or more to implement (probably a lot more since I have to ask people to test it on all kinds of GPUs), and would most likely also introduce many new bugs.

**Comment by explowz** [comment] 2022-03-29 18:32
I'll try it! Thanks! Could you maybe say an approximate date for when the new version will come out with the CUDA fix? I just want to know if it'd be more proftable to just wait for the fix or try it as it it right now.

**Comment by UnamSanctam** [comment] 2022-03-29 18:37
I'm finishing it right now, but someone reported a possible bug in a previous issue that I'm looking at. Haven't been able to reproduce the bug yet but fixing that (if I can find it) should be the last thing left. Though I also have to test that all the new things work together after it's finished as well. I'm trying to get it finished before the 31st but it might take longer than that if something doesn't work.

**Closed** 2022-04-06 16:36 UTC
