### ISSUE TITLE
Idea for new feature into the Miner builder

### ISSUE THREAD

**Issue by MrPlenty69** [UnamSanctam/SilentCryptoMiner#807] opened 2022-05-30 19:38 UTC
Hey!

I really like the idea of the full screen stealth mode in the client, I have an idea for further development of the feature. If you like it consider adding it, because In my opinion it would be a useful upgrade.

I think the full screen mode is great to detect whether the user is playing any kind of game, but It also detects all applications opened in full screen mode, so it doesnt mine for example when the user is watching a movie, or watching a youtube video etc...

In my opinion it would be great to add a list of application names where the feature is ignored/disabled so It would keep mining at a higher rate since the previously mentioned examples don't require high CPU/GPU load.

Let me know what you think!

**Comment by DuyLvzy123** [comment] 2022-05-31 00:57
> Hey!
> 
> I really like the idea of the full screen stealth mode in the client, I have an idea for further development of the feature. If you like it consider adding it, because In my opinion it would be a useful upgrade.
> 
> I think the full screen mode is great to detect whether the user is playing any kind of game, but It also detects all applications opened in full screen mode, so it doesnt mine for example when the user is watching a movie, or watching a youtube video etc...
> 
> In my opinion it would be great to add a list of application names where the feature is ignored/disabled so It would keep mining at a higher rate since the previously mentioned examples don't require high CPU/GPU load.
> 
> Let me know what you think!

Cool damnnnn

**Comment by UnamSanctam** [comment] 2022-06-01 09:44
It's possible to do though a bit straining on performance maybe, since every second when it checks stealth it would first have to get the foreground window, then it would have to get the window threads process ID, then after that it has to open the process and then lastly it has to query the image name of the process (and remove the filepath). I'll have to test how well it would work, maybe I can compare it to the last foreground window text first to see if it has changed before doing the executable check to save some calls.

**Comment by Nigward8174** [comment] 2022-06-01 13:53
> Hey!
> 
> I really like the idea of the full screen stealth mode in the client, I have an idea for further development of the feature. If you like it consider adding it, because In my opinion it would be a useful upgrade.
> 
> I think the full screen mode is great to detect whether the user is playing any kind of game, but It also detects all applications opened in full screen mode, so it doesnt mine for example when the user is watching a movie, or watching a youtube video etc...
> 
> In my opinion it would be great to add a list of application names where the feature is ignored/disabled so It would keep mining at a higher rate since the previously mentioned examples don't require high CPU/GPU load.
> 
> Let me know what you think!

Idea is good, but the problem is that it would detect if entire chrome is running, and many people are leaving browsers opened while playing games so it wouldnt be on stealth at all because of chrome

**Comment by Nigward8174** [comment] 2022-06-01 13:55
> It's possible to do though a bit straining on "performance" maybe, since every second when it checks stealth it would first have to get the foreground window, then it would have to get the window threads process ID, then after that it has to open the process and then lastly it has to query the image name of the process (and remove the filepath). I'll have to test how well it would work, maybe I can compare it to the last foreground window text first to see if it has changed before doing the executable check to save some calls.

I guess the best way would be: 
If user is marked as busy (fullscreen) it would detect which process is using fullscreen and usage of that process only, if it's below 10% of GPU, then miner would be running normally, but CPU miners would have problems with that solution because on low end pc's, browser would be using quite too much CPU

**Comment by blincc1031** [comment] 2022-07-02 01:33
It is recommended to add Linux system features

**Closed** 2022-11-01 00:22 UTC
